services:
  - type: web
    name: books-recommendation-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 0
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DB_HOST
        fromDatabase:
          name: books-recommendation-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: books-recommendation-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: books-recommendation-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: books-recommendation-db
          property: password

databases:
  - name: books-recommendation-db
    plan: free
