# Generated by Django 4.2.30 on 2026-04-16 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("book_name", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=150)),
                ("summary", models.TextField(blank=True)),
                ("published_date", models.DateField(blank=True, null=True)),
                ("genre", models.CharField(max_length=50)),
                (
                    "age_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("childeren", "Children"),
                            ("young_adult", "Young Adult"),
                            ("adult", "Adult"),
                        ],
                        max_length=50,
                    ),
                ),
                ("cover_image", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributed_books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
