# Generated by Django 4.2.30 on 2026-04-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_book_age_group_userprefrence_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="review_test",
            new_name="review_text",
        ),
    ]
